branches:
  only:
    - master
    - devel
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - git submodule foreach git checkout master 
  - pip freeze
  - python setup.py install

install:
  - python qalab/qalab.py selenium -m hub -i
  - python qalab/qalab.py selenium -m node -i

before_script:
  - python qalab/qalab.py selenium -m hub -s &
  - python qalab/qalab.py selenium -m node -s &

script:
  - timeout 10
  - timeout 3 telnet localhost 11000
  - timeout 3 telnet localhost 11001

