language: python
python:
  - "3.6"
before_install:
  - echo "travis before_install"
intall:
  - echo "travis install"
  - pip install -r requirements.txt

before_script:
  - echo "travis before_script"

script:
  - git submodule foreach git checkout master
