branches:
  only:
  - master
  - devel
addons:
  sonarqube:
    branches:
    - master
    - devel
    token:
      secure: pypMDUhJ/ePGSgRPPU8mHN4Fbe8k+cl2NPtiw5FN1lqWQ+tjRkmmFEH+vGIEkx8oIl6bU3qZSbjNDb22yXF63HBOngPs2tZb9hcz3HGAyq05nuBJVErTZen+ky/ZuJRX/dQzCPYsndqkAcZljQbk4kmBuGQk7L+FKScxbeM/OtujgUklKDiAWRbMt7YbSmH22TNwfftDg/Yysry13v106hSAe2N7XSFnMZuSZtQJ3ObNteKlw6cP75uf3QGzXmSVnMjSzw8a/z7IoxfK03RZiV8WI5duVMFeFvlQGXbAVT9Hk4MHEp7hItTcam4ouO1tZzB0XU4d6Lr+dVcK6s997HslVrHeGadcEGQetMRtZQvrGTGEyxhiTQrZw3bOnCtFjktvNXIpVPdAvH0XninPIWlxmYSBnuF7Er+pH3RLjnadNBAgPT1EktEvvzJcD6w8aR1RpHwhb7etc7z+EXlPt6UMq9bquKCifavhLoZ4rI71eOSn3ToFyo1Cfq7dP/COvLmXsX+pUGTOtTXYZIUvdtG8sFTFeq5U/N5PvyW9WAyrAEjwa+OvmhxiRmawxky8wiVwyG5p0a3+kJcBdsM5WZJe0OGvPQqDDD6lfKmdteYXcN/0MCnWkBXrVpxw7vHxNKsk3dCqFOixJzfTJnxMWqcUSROPF8/bngmGH9B8J3M=
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
before_install:
- git submodule foreach git checkout master
- pip freeze
- python setup.py build
- python setup.py install
install:
- python qalab/qalab.py selenium -m hub -i
- python qalab/qalab.py selenium -m node -i
before_script:
- python qalab/qalab.py selenium -m hub -s -p lin64 &
- python qalab/qalab.py selenium -m node -s -p lin64 &
script:
- sleep 10
- nc -z -v -w5 localhost 11000
- nc -z -v -w5 localhost 11001
after_script:
- sonar-scanner -X -Dsonar.host.url=http://qalab.tk:82
