build: off
branches:
  only:
    - master
    - devel
environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"

install:
  - "%PYTHON%\\python.exe setup.py install"
  - "%PYTHON%\\python.exe qalab\\qalab.py selenium -m hub -i"
  - "%PYTHON%\\python.exe qalab\\qalab.py selenium -m node -i"

before_test:
  - cmd \k \"%PYTHON%\\python.exe qalab\\qalab.py selenium -m hub -s\"
  - cmd \k \"%PYTHON%\\python.exe qalab\\qalab.py selenium -m node -s\"

test_script:
  - "telnet localhost 11000"
  - "telnet localhost 11001"
